export const mockTickets = [
  {
    id: 1,
    title: "Ticket 1",
    description: "Ticket 1 description",
    priority: "High",
    status: "Open",
    assignedTo: "Lovish",
    createdBy: "Lovish",
    time: "5:00",
  },
  {
    id: 2,
    title: "Ticket 2",
    description: "Ticket 2 description",
    priority: "Medium",
    status: "Open",
    assignedTo: "Lovish",
    createdBy: "Lovish",
    time: "1:00",
  },
  {
    id: 3,
    title: "Ticket 3",
    description: "Ticket 3 description",
    priority: "Low",
    status: "Open",
    assignedTo: "Lovish",
    createdBy: "Lovish",
    time: "10.00",
  },
  {
    id: 4,
    title: "Ticket 4",
    description: "Ticket 4 description",
    priority: "High",
    status: "Open",
    assignedTo: "Lovish",
    createdBy: "Lovish",
    time: "11.00",
  },
];
